#!/usr/bin/env bash
set -eo pipefail

for (( i=0; i <= $#; i++ )); do
  declare -x "ARG$i"="${!i}"
done

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

unset $(git rev-parse --local-env-vars 2>/dev/null || echo '') && npx moon run :lint :typecheck --affected --status=staged --concurrency=4

